### ISSUE TITLE
Does not work on touch screens

### ISSUE THREAD

**Issue by zeeshanjan82** [seanhess/html5-drag-drop-anything#1]
This does not work on touch screens.

**Comment by seanhess** [comment]
Sadly, HTML5 drag and drop is not supported by current gen mobile browsers. This talk was about how to use the new HTML5 api, and it won't work until the browsers implement it. 

http://caniuse.com/#feat=dragndrop

To get it to work on mobile, you wouldn't be able to use this api, and would have to use touch events manually.
